### PR TITLE
New hooks for GatherManager plugin

### PR DESCRIPTION
**Pull request by Xariman**
Added hooks:
OnAirEventDrop, OnControlTownEventDrop, OnLootFrenzyTownEventSpawn -> void OnEventDrop(GameObject source, object eventType, List<ItemObject> items)
OnLootCaseOpen -> void OnLootCaseOpen(ItemComponentLootCase component, List<ItemObject> items)
OnExplodableMiningRockDrop -> void OnExplodableMiningRockDrop(GameObject source, ExplodableMiningRock rock, List<ItemObject> items)
OnDisassembleVehicleDrop -> void OnDisassembleVehicleDrop(GameObject source, VehicleStatManager vehicle, List<ItemObject> items)
OnVehicleCorpseLootDrop -> void OnVehicleCorpseLootDrop(GameObject source, VehicleCorpseLoot vehicle, List<ItemObject> items)

### CODE REVIEW

**Comment by Xariman** [comment]
Itemv2 GatherManager Extended - https://pastebin.com/PDebgxWz

**Comment by Xariman** [comment]
Need update one hook wait.

**Comment by Xariman** [comment]
{
          "Type": "Simple",
          "Hook": {
            "InjectionIndex": 38,
            "ReturnBehavior": 0,
            "ArgumentBehavior": 4,
            "ArgumentString": "this, a0, v0,  l1",
            "HookTypeName": "Simple",
            "Name": "OnLootCaseOpen",
            "HookName": "OnLootCaseOpen",
            "AssemblyName": "Assembly-CSharp.dll",
            "TypeName": "ItemComponentLootCase",
            "Flagged": false,
            "Signature": {
              "Exposure": 2,
              "Name": "OpenCase",
              "ReturnType": "System.Void",
              "Parameters": [
                "ItemObject"
              ]
            },
            "MSILHash": "00UTzCmpZfSEBg71t/e4BMQPWhmJaGcq0xeqbNNQqUQ=",
            "BaseHookName": null,
            "HookCategory": "Item"
          }
        },

void OnLootCaseOpen(ItemComponentLootCase component, Inventory container, ItemObject parent, List<ItemObject> items)

**Comment by VladimirKzi** [comment]
To configure such a number of options loot is more appropriate to use LootConfig, but the hooks are good, I will be glad if they add.

**Comment by Xariman** [comment]
LootConfig is not very flexible. You can not change loot list depending on player or time or position.

**Comment by Xariman** [comment]
OnLootCaseOpen can cause a problem if you multiply count of boost items, they can be turned into dust. one more case can be built from dust. this can be used as a duplication. I think this hook makes sense, but people need to know what they're doing.

**Comment by lukespragg** [comment]
Manually merged with some renames and formatting changes.

**Pull request closed without merging**
