### PR TITLE
Update master from develop

### PR DESCRIPTION
**Pull request by lukespragg**

### CODE REVIEW

**Comment by KuroFR** [comment]
luke your update wont work in my server that make version older after oxide update.
ive make steam update and after that the oxide update but won't work, ok for config's ?

**Comment by lukespragg** [comment]
Sounds like you're using an old build. Also, please use our forums at oxidemod.org, not here.

**Comment by KuroFR** [comment]
hum ive update all and the oxide update of rox server's is directly linked too github i don't now why its wont work
my game make update on steam the 4.8 mo update's ^^
do you now why ?

**Comment by lukespragg** [comment]
Please use our forums at oxidemod.org for general support, not here.

**Comment by KuroFR** [comment]
ok sry and thx for responding at me

**Pull request merged**
